config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root "markets#index"

  resources :markets, only: [:index, :show]
  resources :vendors, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  def index
    market_service = MarketService.new
    @markets = market_service.all_markets
  end

  def show
    market_id = params[:id]
    market_service = MarketService.new
    @market = market_service.find_market(market_id)
  end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  def show
    vendor_id = params[:id]
    vendor_service = VendorService.new
    vendor_data = vendor_service.find_vendor(vendor_id)
    @vendor = Vendor.new(vendor_data)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/markets_helper.rb
module MarketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarketMoneyFe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    </div>
    <%= render partial: "shared/nav" %>

      <div id="mainBody" class="container">
        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, class: name %>
        <% end %>
      </div>
    <%= yield %>
  </body>
</html>

app/views/markets/index.html.erb
<head>
  <%= stylesheet_link_tag 'styles' %>
</head>

<h1>Markets</h1>

<div class="flex-table">
  <div class="flex-row header">
    <div class="flex-cell">Name</div>
    <div class="flex-cell">City</div>
    <div class="flex-cell">State</div>
    <div class="flex-cell"></div>
  </div>

  <% @markets.each do |market| %>
    <div class="flex-row">
      <div class="flex-cell"><%= market.name %></div>
      <div class="flex-cell"><%= market.city %></div>
      <div class="flex-cell"><%= market.state %></div>
      <div class="flex-cell"><%= link_to 'More Info', market_path(market.id), class: 'button' %></div>
    </div>
  <% end %>
</div>

app/views/markets/show.html.erb
<h1 style="text-align:center"><%= @market.name %></h1>

<p style="text-align:center">
  <%= @market.street_address %><br>
  <%= @market.city_state_zip %>
</p>

<h2>Vendors at our Market:</h2>
<ul>
  <% @market.vendors.each do |vendor| %>
      <li><%= link_to vendor.name, vendor_path(vendor.id) %></li>
  <% end %>
</ul>

app/views/shared/_nav.html.erb
<div>
  <nav>
  <%= link_to 'Home', root_path %>
  </nav>
</div>

app/views/vendors/show.html.erb
<h1><%= @vendor.name %></h1>

<p>Contact: <%= @vendor.contact_name %></p>
<p>Phone: <%= @vendor.contact_phone %></p>
<p>Accepts Credit: <%= @vendor.credit_accepted ? 'Yes' : 'No' %></p>
<p>Description: <%= @vendor.description %></p>